### ISSUE TITLE
Laravel Support

### ISSUE THREAD

**Issue by ManojKiranA** [seregazhuk/php-watcher#15]
Add Support for Laravel by adding Console Command

**Comment by seregazhuk** [comment]
I don't see any problem with using the watcher with Laravel. What is your issue about?

**Comment by ManojKiranA** [comment]
i have clearly mentioned as  adding console command

for Example: My App Name is Demo

Instead of `php-watcher Demo`

There must of Some Sort of Command as

`php artisan Watch`

**Comment by seregazhuk** [comment]
Actually, it is not clear for those how don't use Laravel. I think that what you want here should be implemented as a separate package, not in this one. I don't want to couple this package to any framework.

**Comment by gorbunov** [comment]
@seregazhuk I'm a Laravel developer, and I see only one possible scope for php-watcher:
1. There is long-running queue processing command, but there is already "sync" mode for development, which just processes queue immediately on requests (which is also default, so, no good reason to implement this) I actually use php-watcher for this restarting this queue inside docker container.

Also, for the actual feature asked, there is a bundled `artisan serve` command that does exactly whats requested: starts laravel app with internal php http server.

**Comment by seregazhuk** [comment]
@gorbunov so, there is no need to couple to Console Command or something like that? If someone wants to make `artisan watch` command - this can be implemented in a separate package "laravel-php-watcher" or something)

**Comment by gorbunov** [comment]
@seregazhuk yes, I think its not needed: There is no long-running processes to watch out-of-the-box in laravel in development mode, there is existing command to serve app as traditional http requests, any other complex behavior wouldn't benefit from any implementation internal watching. (Also no reason to bundle it with production code of any laravel app) 
I'd say this should be just closed.

**Comment by seregazhuk** [comment]
@gorbunov thank you!
