### ISSUE TITLE
Implement custom spinner

### ISSUE THREAD

**Issue by seregazhuk** [seregazhuk/php-watcher#17]
We need to decouple from [alecrabbit/php-console-spinner](https://github.com/alecrabbit/php-console-spinner). It has a lot of dependencies, for example under the hood it requires laravel container 6.0 and thus cannot be installed on the latest laravel version.

The logic to render a spinner is pretty simple and can be easily implemented right here inside the library.

**Comment by alecrabbit** [comment]
Hi @seregazhuk!
It will be a pleasure for me if you'll consider to return to use my package 😃 
I mean new one - [alecrabbit/php-cli-snake](https://github.com/alecrabbit/php-cli-snake)
it has literally zero dependencies, but still offers some useful features

**Comment by seregazhuk** [comment]
Hi @alecrabbit Thank you! That's great 👍 I'll look through it.

**Comment by seregazhuk** [comment]
@alecrabbit [done](https://github.com/seregazhuk/php-watcher/pull/44)! 👍
