### ISSUE TITLE
Make it compatible with Symfony 5

### ISSUE THREAD

**Issue by mmoreram** [seregazhuk/php-watcher#57]
Some required libraries are blocked to Symfony^4, blocking then all project requiring this watcher. We could make some push to them by adding some PRs, or just checking how to uncouple from them.

**Comment by seregazhuk** [comment]
Have created a PR in `yosymfony/resource-watcher` for Symfony 5 upgrade.

https://github.com/yosymfony/resource-watcher/pull/8/commits

**Comment by yosymfony** [comment]
PR merged already

**Comment by seregazhuk** [comment]
Great news! The watcher is now compatible with Symfony 5 👍
