### ISSUE TITLE
Make php-cli-snake an optional requirement

### ISSUE THREAD

**Issue by mmoreram** [seregazhuk/php-watcher#60]
I would only make it a required library if is enabled. Otherwise, disable the loader.

**Comment by seregazhuk** [comment]
Why? What's wrong with this dependency? 🤔

**Comment by mmoreram** [comment]
Nothing at all. By adding as a dependency in this project makes all projects using this watcher a strong dependency, even if we don't use the loader. This dep could be defined as an optional requirement :)

**Comment by seregazhuk** [comment]
But this library has actually zero dependencies :) I think it is OK to keep it 🤷‍♂

**Comment by mmoreram** [comment]
Ok
