### ISSUE TITLE
Console colours

### ISSUE THREAD

**Issue by brendt** [seregazhuk/php-watcher#65]
Console colours don't seem to work, am I doing something wrong? 

This is the output I'm getting:

<img width="720" alt="Screen Shot 2020-02-27 at 13 29 43" src="https://user-images.githubusercontent.com/6905297/75445224-4ad0fa80-5965-11ea-920f-065382b6a485.png">

It should be this:

<img width="773" alt="Screen Shot 2020-02-27 at 13 29 52" src="https://user-images.githubusercontent.com/6905297/75445220-486ea080-5965-11ea-9655-a00626857221.png">

**Comment by seregazhuk** [comment]
Actually, I'm not an expert with console colors. Maybe it is because of spinner 🤔 Can you try to run it with the following option `--no-spinner` and see what happens?

**Comment by brendt** [comment]
Disabling the spinner doesn't solve it. It's not that big an issue though, but if someone knows the solution I'd like to hear about it 😁

**Comment by seregazhuk** [comment]
Let’s ping @alecrabbit then. Hope he will help us 💪

**Comment by alecrabbit** [comment]
clearly something is wrong
@brendt information you've provided doesn't give me any ideas

**Comment by seregazhuk** [comment]
Currently closing due to no feedback 🤔
